# Generated by Django 2.1.5 on 2019-03-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profilePic',
            new_name='profile_image',
        ),
    ]
