# Generated by Django 2.1.5 on 2019-03-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190313_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
