# Generated by Django 2.1.5 on 2019-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
